//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for buyerSellerId complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="buyerSellerId">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="LEI" type="{http://deutsche-boerse.com/DBRegHub}LEI"/>
 *         &lt;element name="MIC">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NATIONAL_ID_CCPT">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="((FI)[A-Za-z0-9\-\+]{1,33})|((LV)[A-Za-z0-9\-]{1,33})|([A-Za-z]{2,2}[A-Za-z0-9]{1,33})"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NATIONAL_ID_NIDN">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="((FI)[A-Za-z0-9\-\+]{1,33})|((LV)[A-Za-z0-9\-]{1,33})|([A-Za-z]{2,2}[A-Za-z0-9]{1,33})"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NATIONAL_ID_CONCAT">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[A-Za-z]{2,2}(17|18|19|20|21)[0-9]{2}((0)[1-9]|(1)[012])((0)[1-9]|(1|2)[0-9]|(3)[01])[A-Za-z]{1}[A-Za-z#]{4}[A-Za-z]{1}[A-Za-z#]{4}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NATIONAL_ID_DERCON">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INTC">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;enumeration value="INTC"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INTERNAL_PARTY_ID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="35"/>
 *               &lt;pattern value="[A-Za-z 0-9]{1,35}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INVALID_PARTY">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="35"/>
 *               &lt;pattern value="[A-Za-z 0-9]{1,35}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "buyerSellerId", propOrder = {
    "lei",
    "mic",
    "nationalidccpt",
    "nationalidnidn",
    "nationalidconcat",
    "nationaliddercon",
    "intc",
    "internalpartyid",
    "invalidparty"
})
public class BuyerSellerId {

    @XmlElement(name = "LEI")
    protected String lei;
    @XmlElement(name = "MIC")
    protected String mic;
    @XmlElement(name = "NATIONAL_ID_CCPT")
    protected String nationalidccpt;
    @XmlElement(name = "NATIONAL_ID_NIDN")
    protected String nationalidnidn;
    @XmlElement(name = "NATIONAL_ID_CONCAT")
    protected String nationalidconcat;
    @XmlElement(name = "NATIONAL_ID_DERCON")
    protected String nationaliddercon;
    @XmlElement(name = "INTC")
    protected String intc;
    @XmlElement(name = "INTERNAL_PARTY_ID")
    protected String internalpartyid;
    @XmlElement(name = "INVALID_PARTY")
    protected String invalidparty;

    /**
     * Gets the value of the lei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEI() {
        return lei;
    }

    /**
     * Sets the value of the lei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEI(String value) {
        this.lei = value;
    }

    /**
     * Gets the value of the mic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIC() {
        return mic;
    }

    /**
     * Sets the value of the mic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIC(String value) {
        this.mic = value;
    }

    /**
     * Gets the value of the nationalidccpt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNATIONALIDCCPT() {
        return nationalidccpt;
    }

    /**
     * Sets the value of the nationalidccpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNATIONALIDCCPT(String value) {
        this.nationalidccpt = value;
    }

    /**
     * Gets the value of the nationalidnidn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNATIONALIDNIDN() {
        return nationalidnidn;
    }

    /**
     * Sets the value of the nationalidnidn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNATIONALIDNIDN(String value) {
        this.nationalidnidn = value;
    }

    /**
     * Gets the value of the nationalidconcat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNATIONALIDCONCAT() {
        return nationalidconcat;
    }

    /**
     * Sets the value of the nationalidconcat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNATIONALIDCONCAT(String value) {
        this.nationalidconcat = value;
    }

    /**
     * Gets the value of the nationaliddercon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNATIONALIDDERCON() {
        return nationaliddercon;
    }

    /**
     * Sets the value of the nationaliddercon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNATIONALIDDERCON(String value) {
        this.nationaliddercon = value;
    }

    /**
     * Gets the value of the intc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTC() {
        return intc;
    }

    /**
     * Sets the value of the intc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTC(String value) {
        this.intc = value;
    }

    /**
     * Gets the value of the internalpartyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTERNALPARTYID() {
        return internalpartyid;
    }

    /**
     * Sets the value of the internalpartyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTERNALPARTYID(String value) {
        this.internalpartyid = value;
    }

    /**
     * Gets the value of the invalidparty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVALIDPARTY() {
        return invalidparty;
    }

    /**
     * Sets the value of the invalidparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVALIDPARTY(String value) {
        this.invalidparty = value;
    }

}
