//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for configurableFields complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configurableFields">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userField1" type="{http://deutsche-boerse.com/DBRegHub}string50" minOccurs="0"/>
 *         &lt;element name="userField2" type="{http://deutsche-boerse.com/DBRegHub}string50" minOccurs="0"/>
 *         &lt;element name="userField3" type="{http://deutsche-boerse.com/DBRegHub}string50" minOccurs="0"/>
 *         &lt;element name="userField4" type="{http://deutsche-boerse.com/DBRegHub}string50" minOccurs="0"/>
 *         &lt;element name="userField5" type="{http://deutsche-boerse.com/DBRegHub}string50" minOccurs="0"/>
 *         &lt;element name="userField6" type="{http://deutsche-boerse.com/DBRegHub}string50" minOccurs="0"/>
 *         &lt;element name="userField7" type="{http://deutsche-boerse.com/DBRegHub}string50" minOccurs="0"/>
 *         &lt;element name="userField8" type="{http://deutsche-boerse.com/DBRegHub}string50" minOccurs="0"/>
 *         &lt;element name="userField9" type="{http://deutsche-boerse.com/DBRegHub}string50" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configurableFields", propOrder = {
    "userField1",
    "userField2",
    "userField3",
    "userField4",
    "userField5",
    "userField6",
    "userField7",
    "userField8",
    "userField9"
})
public class ConfigurableFields {

    protected String userField1;
    protected String userField2;
    protected String userField3;
    protected String userField4;
    protected String userField5;
    protected String userField6;
    protected String userField7;
    protected String userField8;
    protected String userField9;

    /**
     * Gets the value of the userField1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField1() {
        return userField1;
    }

    /**
     * Sets the value of the userField1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField1(String value) {
        this.userField1 = value;
    }

    /**
     * Gets the value of the userField2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField2() {
        return userField2;
    }

    /**
     * Sets the value of the userField2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField2(String value) {
        this.userField2 = value;
    }

    /**
     * Gets the value of the userField3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField3() {
        return userField3;
    }

    /**
     * Sets the value of the userField3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField3(String value) {
        this.userField3 = value;
    }

    /**
     * Gets the value of the userField4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField4() {
        return userField4;
    }

    /**
     * Sets the value of the userField4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField4(String value) {
        this.userField4 = value;
    }

    /**
     * Gets the value of the userField5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField5() {
        return userField5;
    }

    /**
     * Sets the value of the userField5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField5(String value) {
        this.userField5 = value;
    }

    /**
     * Gets the value of the userField6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField6() {
        return userField6;
    }

    /**
     * Sets the value of the userField6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField6(String value) {
        this.userField6 = value;
    }

    /**
     * Gets the value of the userField7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField7() {
        return userField7;
    }

    /**
     * Sets the value of the userField7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField7(String value) {
        this.userField7 = value;
    }

    /**
     * Gets the value of the userField8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField8() {
        return userField8;
    }

    /**
     * Sets the value of the userField8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField8(String value) {
        this.userField8 = value;
    }

    /**
     * Gets the value of the userField9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserField9() {
        return userField9;
    }

    /**
     * Sets the value of the userField9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserField9(String value) {
        this.userField9 = value;
    }

}
