//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="delegation" type="{http://deutsche-boerse.com/DBRegHub}mifirDelegation" minOccurs="0"/>
 *         &lt;element name="counterpartyDetails" type="{http://deutsche-boerse.com/DBRegHub}mifirCounterpartyDetails" minOccurs="0"/>
 *         &lt;element name="transmission" type="{http://deutsche-boerse.com/DBRegHub}mifirTransmission" minOccurs="0"/>
 *         &lt;element name="transactionDetails" type="{http://deutsche-boerse.com/DBRegHub}mifirTransaction" minOccurs="0"/>
 *         &lt;element name="instrumentDetails" type="{http://deutsche-boerse.com/DBRegHub}mifirInstrumentDetails" minOccurs="0"/>
 *         &lt;element name="otherDetails" type="{http://deutsche-boerse.com/DBRegHub}mifirOtherDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirDetails", propOrder = {
    "delegation",
    "counterpartyDetails",
    "transmission",
    "transactionDetails",
    "instrumentDetails",
    "otherDetails"
})
public class MifirDetails {

    protected MifirDelegation delegation;
    protected MifirCounterpartyDetails counterpartyDetails;
    protected MifirTransmission transmission;
    protected MifirTransaction transactionDetails;
    protected MifirInstrumentDetails instrumentDetails;
    protected MifirOtherDetails otherDetails;

    /**
     * Gets the value of the delegation property.
     * 
     * @return
     *     possible object is
     *     {@link MifirDelegation }
     *     
     */
    public MifirDelegation getDelegation() {
        return delegation;
    }

    /**
     * Sets the value of the delegation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MifirDelegation }
     *     
     */
    public void setDelegation(MifirDelegation value) {
        this.delegation = value;
    }

    /**
     * Gets the value of the counterpartyDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MifirCounterpartyDetails }
     *     
     */
    public MifirCounterpartyDetails getCounterpartyDetails() {
        return counterpartyDetails;
    }

    /**
     * Sets the value of the counterpartyDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MifirCounterpartyDetails }
     *     
     */
    public void setCounterpartyDetails(MifirCounterpartyDetails value) {
        this.counterpartyDetails = value;
    }

    /**
     * Gets the value of the transmission property.
     * 
     * @return
     *     possible object is
     *     {@link MifirTransmission }
     *     
     */
    public MifirTransmission getTransmission() {
        return transmission;
    }

    /**
     * Sets the value of the transmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link MifirTransmission }
     *     
     */
    public void setTransmission(MifirTransmission value) {
        this.transmission = value;
    }

    /**
     * Gets the value of the transactionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MifirTransaction }
     *     
     */
    public MifirTransaction getTransactionDetails() {
        return transactionDetails;
    }

    /**
     * Sets the value of the transactionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MifirTransaction }
     *     
     */
    public void setTransactionDetails(MifirTransaction value) {
        this.transactionDetails = value;
    }

    /**
     * Gets the value of the instrumentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MifirInstrumentDetails }
     *     
     */
    public MifirInstrumentDetails getInstrumentDetails() {
        return instrumentDetails;
    }

    /**
     * Sets the value of the instrumentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MifirInstrumentDetails }
     *     
     */
    public void setInstrumentDetails(MifirInstrumentDetails value) {
        this.instrumentDetails = value;
    }

    /**
     * Gets the value of the otherDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MifirOtherDetails }
     *     
     */
    public MifirOtherDetails getOtherDetails() {
        return otherDetails;
    }

    /**
     * Sets the value of the otherDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MifirOtherDetails }
     *     
     */
    public void setOtherDetails(MifirOtherDetails value) {
        this.otherDetails = value;
    }

}
