//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirPrice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirPrice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="MONETARY">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *               &lt;pattern value="(-?(0|[1-9][0-9]{0,17})([.][0-9]{1,13})?)?"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PERCENT">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="13"/>
 *               &lt;pattern value="(-?(0|[1-9][0-9]{0,10})([.][0-9]{1,10})?)?"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="YIELD">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="13"/>
 *               &lt;pattern value="(-?(0|[1-9][0-9]{0,10})([.][0-9]{1,10})?)?"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BASIS_POINTS">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *               &lt;pattern value="(-?(0|[1-9][0-9]{0,17})([.][0-9]{1,17})?)?"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PNDG">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;enumeration value="PNDG"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NOAP">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;enumeration value="NOAP"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirPrice", propOrder = {
    "monetary",
    "percent",
    "yield",
    "basispoints",
    "pndg",
    "noap"
})
public class MifirPrice {

    @XmlElement(name = "MONETARY")
    protected String monetary;
    @XmlElement(name = "PERCENT")
    protected String percent;
    @XmlElement(name = "YIELD")
    protected String yield;
    @XmlElement(name = "BASIS_POINTS")
    protected String basispoints;
    @XmlElement(name = "PNDG")
    protected String pndg;
    @XmlElement(name = "NOAP")
    protected String noap;

    /**
     * Gets the value of the monetary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMONETARY() {
        return monetary;
    }

    /**
     * Sets the value of the monetary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMONETARY(String value) {
        this.monetary = value;
    }

    /**
     * Gets the value of the percent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPERCENT() {
        return percent;
    }

    /**
     * Sets the value of the percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPERCENT(String value) {
        this.percent = value;
    }

    /**
     * Gets the value of the yield property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYIELD() {
        return yield;
    }

    /**
     * Sets the value of the yield property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYIELD(String value) {
        this.yield = value;
    }

    /**
     * Gets the value of the basispoints property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBASISPOINTS() {
        return basispoints;
    }

    /**
     * Sets the value of the basispoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBASISPOINTS(String value) {
        this.basispoints = value;
    }

    /**
     * Gets the value of the pndg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPNDG() {
        return pndg;
    }

    /**
     * Sets the value of the pndg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPNDG(String value) {
        this.pndg = value;
    }

    /**
     * Gets the value of the noap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOAP() {
        return noap;
    }

    /**
     * Sets the value of the noap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOAP(String value) {
        this.noap = value;
    }

}
