//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirDelegation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirDelegation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="partialAssistanceFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="partialAssistanceSubmitterId" type="{http://deutsche-boerse.com/DBRegHub}LEI" minOccurs="0"/>
 *         &lt;element name="pairingId">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="32"/>
 *               &lt;pattern value="[A-Z 0-9]+"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirDelegation", propOrder = {
    "partialAssistanceFlag",
    "partialAssistanceSubmitterId",
    "pairingId"
})
public class MifirDelegation {

    protected String partialAssistanceFlag;
    protected String partialAssistanceSubmitterId;
    @XmlElement(required = true)
    protected String pairingId;

    /**
     * Gets the value of the partialAssistanceFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartialAssistanceFlag() {
        return partialAssistanceFlag;
    }

    /**
     * Sets the value of the partialAssistanceFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartialAssistanceFlag(String value) {
        this.partialAssistanceFlag = value;
    }

    /**
     * Gets the value of the partialAssistanceSubmitterId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartialAssistanceSubmitterId() {
        return partialAssistanceSubmitterId;
    }

    /**
     * Sets the value of the partialAssistanceSubmitterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartialAssistanceSubmitterId(String value) {
        this.partialAssistanceSubmitterId = value;
    }

    /**
     * Gets the value of the pairingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPairingId() {
        return pairingId;
    }

    /**
     * Sets the value of the pairingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPairingId(String value) {
        this.pairingId = value;
    }

}
