//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirUnderlyingIndexName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirUnderlyingIndexName">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="underlyingIndexNameAcronym">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="WIBO"/>
 *               &lt;enumeration value="TREA"/>
 *               &lt;enumeration value="TIBO"/>
 *               &lt;enumeration value="TLBO"/>
 *               &lt;enumeration value="SWAP"/>
 *               &lt;enumeration value="STBO"/>
 *               &lt;enumeration value="PRBO"/>
 *               &lt;enumeration value="PFAN"/>
 *               &lt;enumeration value="NIBO"/>
 *               &lt;enumeration value="MAAA"/>
 *               &lt;enumeration value="MOSP"/>
 *               &lt;enumeration value="LIBO"/>
 *               &lt;enumeration value="LIBI"/>
 *               &lt;enumeration value="JIBA"/>
 *               &lt;enumeration value="ISDA"/>
 *               &lt;enumeration value="GCFR"/>
 *               &lt;enumeration value="FUSW"/>
 *               &lt;enumeration value="EUCH"/>
 *               &lt;enumeration value="EUUS"/>
 *               &lt;enumeration value="EURI"/>
 *               &lt;enumeration value="EONS"/>
 *               &lt;enumeration value="EONA"/>
 *               &lt;enumeration value="CIBO"/>
 *               &lt;enumeration value="CDOR"/>
 *               &lt;enumeration value="BUBO"/>
 *               &lt;enumeration value="BBSW"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="underlyingIndexNameFull">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirUnderlyingIndexName", propOrder = {
    "underlyingIndexNameAcronym",
    "underlyingIndexNameFull"
})
public class MifirUnderlyingIndexName {

    protected String underlyingIndexNameAcronym;
    protected String underlyingIndexNameFull;

    /**
     * Gets the value of the underlyingIndexNameAcronym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnderlyingIndexNameAcronym() {
        return underlyingIndexNameAcronym;
    }

    /**
     * Sets the value of the underlyingIndexNameAcronym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnderlyingIndexNameAcronym(String value) {
        this.underlyingIndexNameAcronym = value;
    }

    /**
     * Gets the value of the underlyingIndexNameFull property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnderlyingIndexNameFull() {
        return underlyingIndexNameFull;
    }

    /**
     * Sets the value of the underlyingIndexNameFull property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnderlyingIndexNameFull(String value) {
        this.underlyingIndexNameFull = value;
    }

}
