//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirBuyerDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirBuyerDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="buyerId" type="{http://deutsche-boerse.com/DBRegHub}buyerSellerId"/>
 *         &lt;element name="buyerBranchCountry" type="{http://deutsche-boerse.com/DBRegHub}Country_Code" minOccurs="0"/>
 *         &lt;element name="buyerFirstname" type="{http://deutsche-boerse.com/DBRegHub}nameType" minOccurs="0"/>
 *         &lt;element name="buyerSurname" type="{http://deutsche-boerse.com/DBRegHub}nameType" minOccurs="0"/>
 *         &lt;element name="buyerBirthdate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="(17|18|19|20|21)[0-9]{2}(-)((0)[1-9]|(1)[012])(-)((0)[1-9]|(1|2)[0-9]|(3)[01])"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirBuyerDetails", propOrder = {
    "buyerId",
    "buyerBranchCountry",
    "buyerFirstname",
    "buyerSurname",
    "buyerBirthdate"
})
public class MifirBuyerDetails {

    @XmlElement(required = true)
    protected BuyerSellerId buyerId;
    protected String buyerBranchCountry;
    protected String buyerFirstname;
    protected String buyerSurname;
    protected String buyerBirthdate;

    /**
     * Gets the value of the buyerId property.
     * 
     * @return
     *     possible object is
     *     {@link BuyerSellerId }
     *     
     */
    public BuyerSellerId getBuyerId() {
        return buyerId;
    }

    /**
     * Sets the value of the buyerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyerSellerId }
     *     
     */
    public void setBuyerId(BuyerSellerId value) {
        this.buyerId = value;
    }

    /**
     * Gets the value of the buyerBranchCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerBranchCountry() {
        return buyerBranchCountry;
    }

    /**
     * Sets the value of the buyerBranchCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerBranchCountry(String value) {
        this.buyerBranchCountry = value;
    }

    /**
     * Gets the value of the buyerFirstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerFirstname() {
        return buyerFirstname;
    }

    /**
     * Sets the value of the buyerFirstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerFirstname(String value) {
        this.buyerFirstname = value;
    }

    /**
     * Gets the value of the buyerSurname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerSurname() {
        return buyerSurname;
    }

    /**
     * Sets the value of the buyerSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerSurname(String value) {
        this.buyerSurname = value;
    }

    /**
     * Gets the value of the buyerBirthdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerBirthdate() {
        return buyerBirthdate;
    }

    /**
     * Sets the value of the buyerBirthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerBirthdate(String value) {
        this.buyerBirthdate = value;
    }

}
