//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirBuyer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirBuyer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mifirBuyerDetails" type="{http://deutsche-boerse.com/DBRegHub}mifirBuyerDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="mifirBuyerDecisionMakerDetails" type="{http://deutsche-boerse.com/DBRegHub}mifirBuyerDecisionMakerDetails" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirBuyer", propOrder = {
    "mifirBuyerDetails",
    "mifirBuyerDecisionMakerDetails"
})
public class MifirBuyer {

    protected List<MifirBuyerDetails> mifirBuyerDetails;
    protected List<MifirBuyerDecisionMakerDetails> mifirBuyerDecisionMakerDetails;

    /**
     * Gets the value of the mifirBuyerDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mifirBuyerDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMifirBuyerDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MifirBuyerDetails }
     * 
     * 
     */
    public List<MifirBuyerDetails> getMifirBuyerDetails() {
        if (mifirBuyerDetails == null) {
            mifirBuyerDetails = new ArrayList<MifirBuyerDetails>();
        }
        return this.mifirBuyerDetails;
    }

    /**
     * Gets the value of the mifirBuyerDecisionMakerDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mifirBuyerDecisionMakerDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMifirBuyerDecisionMakerDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MifirBuyerDecisionMakerDetails }
     * 
     * 
     */
    public List<MifirBuyerDecisionMakerDetails> getMifirBuyerDecisionMakerDetails() {
        if (mifirBuyerDecisionMakerDetails == null) {
            mifirBuyerDecisionMakerDetails = new ArrayList<MifirBuyerDecisionMakerDetails>();
        }
        return this.mifirBuyerDecisionMakerDetails;
    }

}
