//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirOtherDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirOtherDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="investmentDecisionId" type="{http://deutsche-boerse.com/DBRegHub}investmentDecisionId" minOccurs="0"/>
 *         &lt;element name="investmentDecisionBranchCountry" type="{http://deutsche-boerse.com/DBRegHub}Country_Code" minOccurs="0"/>
 *         &lt;element name="executionId" type="{http://deutsche-boerse.com/DBRegHub}investmentExecutionId" minOccurs="0"/>
 *         &lt;element name="supervisingBranchCountry" type="{http://deutsche-boerse.com/DBRegHub}Country_Code" minOccurs="0"/>
 *         &lt;element name="waiverIndicator" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="19"/>
 *               &lt;pattern value="((RFPT|NLIQ|OILQ|PRIC|SIZE|ILQD)(,(RFPT|NLIQ|OILQ|PRIC|SIZE|ILQD)){0,3})"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="shortSellingIndicator" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="SESH"/>
 *               &lt;enumeration value="SSEX"/>
 *               &lt;enumeration value="SELL"/>
 *               &lt;enumeration value="UNDI"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="otcPostTradeIndicator" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="54"/>
 *               &lt;pattern value="((BENC|ACTX|LRGS|ILQD|SIZE|AMND|CANC|SDIV|RPRI|DUPL|TNCP|TPAC|XFPH)(,(BENC|ACTX|LRGS|ILQD|SIZE|AMND|CANC|SDIV|RPRI|DUPL|TNCP|TPAC|XFPH)){0,10})"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="commodityDerivativeIndicator" type="{http://deutsche-boerse.com/DBRegHub}YesNo" minOccurs="0"/>
 *         &lt;element name="sftrIndicator" type="{http://deutsche-boerse.com/DBRegHub}YesNo" minOccurs="0"/>
 *         &lt;element name="clientType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="R"/>
 *               &lt;enumeration value="P"/>
 *               &lt;enumeration value=" "/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="orderType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="P"/>
 *               &lt;enumeration value="A"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="directedOrderFlag" type="{http://deutsche-boerse.com/DBRegHub}YesNo" minOccurs="0"/>
 *         &lt;element name="liqpFlag" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="E"/>
 *               &lt;enumeration value="C"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="orderGroupId" type="{http://deutsche-boerse.com/DBRegHub}string50" minOccurs="0"/>
 *         &lt;element name="toaxFlag" type="{http://deutsche-boerse.com/DBRegHub}YesNo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirOtherDetails", propOrder = {
    "investmentDecisionId",
    "investmentDecisionBranchCountry",
    "executionId",
    "supervisingBranchCountry",
    "waiverIndicator",
    "shortSellingIndicator",
    "otcPostTradeIndicator",
    "commodityDerivativeIndicator",
    "sftrIndicator",
    "clientType",
    "orderType",
    "directedOrderFlag",
    "liqpFlag",
    "orderGroupId",
    "toaxFlag"
})
public class MifirOtherDetails {

    protected InvestmentDecisionId investmentDecisionId;
    protected String investmentDecisionBranchCountry;
    protected InvestmentExecutionId executionId;
    protected String supervisingBranchCountry;
    protected String waiverIndicator;
    protected String shortSellingIndicator;
    protected String otcPostTradeIndicator;
    @XmlSchemaType(name = "string")
    protected YesNo commodityDerivativeIndicator;
    @XmlSchemaType(name = "string")
    protected YesNo sftrIndicator;
    protected String clientType;
    protected String orderType;
    @XmlSchemaType(name = "string")
    protected YesNo directedOrderFlag;
    protected String liqpFlag;
    protected String orderGroupId;
    @XmlSchemaType(name = "string")
    protected YesNo toaxFlag;

    /**
     * Gets the value of the investmentDecisionId property.
     * 
     * @return
     *     possible object is
     *     {@link InvestmentDecisionId }
     *     
     */
    public InvestmentDecisionId getInvestmentDecisionId() {
        return investmentDecisionId;
    }

    /**
     * Sets the value of the investmentDecisionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestmentDecisionId }
     *     
     */
    public void setInvestmentDecisionId(InvestmentDecisionId value) {
        this.investmentDecisionId = value;
    }

    /**
     * Gets the value of the investmentDecisionBranchCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvestmentDecisionBranchCountry() {
        return investmentDecisionBranchCountry;
    }

    /**
     * Sets the value of the investmentDecisionBranchCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvestmentDecisionBranchCountry(String value) {
        this.investmentDecisionBranchCountry = value;
    }

    /**
     * Gets the value of the executionId property.
     * 
     * @return
     *     possible object is
     *     {@link InvestmentExecutionId }
     *     
     */
    public InvestmentExecutionId getExecutionId() {
        return executionId;
    }

    /**
     * Sets the value of the executionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestmentExecutionId }
     *     
     */
    public void setExecutionId(InvestmentExecutionId value) {
        this.executionId = value;
    }

    /**
     * Gets the value of the supervisingBranchCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupervisingBranchCountry() {
        return supervisingBranchCountry;
    }

    /**
     * Sets the value of the supervisingBranchCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupervisingBranchCountry(String value) {
        this.supervisingBranchCountry = value;
    }

    /**
     * Gets the value of the waiverIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaiverIndicator() {
        return waiverIndicator;
    }

    /**
     * Sets the value of the waiverIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaiverIndicator(String value) {
        this.waiverIndicator = value;
    }

    /**
     * Gets the value of the shortSellingIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortSellingIndicator() {
        return shortSellingIndicator;
    }

    /**
     * Sets the value of the shortSellingIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortSellingIndicator(String value) {
        this.shortSellingIndicator = value;
    }

    /**
     * Gets the value of the otcPostTradeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtcPostTradeIndicator() {
        return otcPostTradeIndicator;
    }

    /**
     * Sets the value of the otcPostTradeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtcPostTradeIndicator(String value) {
        this.otcPostTradeIndicator = value;
    }

    /**
     * Gets the value of the commodityDerivativeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getCommodityDerivativeIndicator() {
        return commodityDerivativeIndicator;
    }

    /**
     * Sets the value of the commodityDerivativeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setCommodityDerivativeIndicator(YesNo value) {
        this.commodityDerivativeIndicator = value;
    }

    /**
     * Gets the value of the sftrIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getSftrIndicator() {
        return sftrIndicator;
    }

    /**
     * Sets the value of the sftrIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setSftrIndicator(YesNo value) {
        this.sftrIndicator = value;
    }

    /**
     * Gets the value of the clientType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * Sets the value of the clientType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientType(String value) {
        this.clientType = value;
    }

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the directedOrderFlag property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getDirectedOrderFlag() {
        return directedOrderFlag;
    }

    /**
     * Sets the value of the directedOrderFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setDirectedOrderFlag(YesNo value) {
        this.directedOrderFlag = value;
    }

    /**
     * Gets the value of the liqpFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiqpFlag() {
        return liqpFlag;
    }

    /**
     * Sets the value of the liqpFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiqpFlag(String value) {
        this.liqpFlag = value;
    }

    /**
     * Gets the value of the orderGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderGroupId() {
        return orderGroupId;
    }

    /**
     * Sets the value of the orderGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderGroupId(String value) {
        this.orderGroupId = value;
    }

    /**
     * Gets the value of the toaxFlag property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getToaxFlag() {
        return toaxFlag;
    }

    /**
     * Sets the value of the toaxFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setToaxFlag(YesNo value) {
        this.toaxFlag = value;
    }

}
