//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirTransaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirTransaction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trnRefNumber" type="{http://deutsche-boerse.com/DBRegHub}Ref_ID2" minOccurs="0"/>
 *         &lt;element name="tradingVenueTrnIdCode" type="{http://deutsche-boerse.com/DBRegHub}Ref_ID2" minOccurs="0"/>
 *         &lt;element name="venue">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;pattern value="[A-Za-z0-9]{4,4}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tradeTime" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="((0|1)[0-9]|(2)[0-4])(:)((0|1|2|3|4|5)[0-9])(:)((0|1|2|3|4|5)[0-9])(.)([0-9]{6})(Z|((\+|-)((0|1|2|3|4|5)[0-9])(:)((0|1|2|3|4|5)[0-9])))"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="mifirTradingCapacity" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="DEAL"/>
 *               &lt;enumeration value="MTCH"/>
 *               &lt;enumeration value="AOTC"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="quantity" type="{http://deutsche-boerse.com/DBRegHub}mifirQuantity" minOccurs="0"/>
 *         &lt;element name="quantityCurrency" type="{http://deutsche-boerse.com/DBRegHub}Currency_Code" minOccurs="0"/>
 *         &lt;element name="notionalIncreaseDecrease" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="INCR"/>
 *               &lt;enumeration value="DECR"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="price" type="{http://deutsche-boerse.com/DBRegHub}mifirPrice" minOccurs="0"/>
 *         &lt;element name="priceCurrency" type="{http://deutsche-boerse.com/DBRegHub}Currency_Code" minOccurs="0"/>
 *         &lt;element name="netAmount" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="19"/>
 *               &lt;pattern value="((0|[1-9][0-9]{0,17})([.][0-9]{1,5})?)?"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="upfrontPayment" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *               &lt;pattern value="(-?(0|[1-9][0-9]{0,17})([.][0-9]{1,5})?)?"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="upfrontPaymentCurrency" type="{http://deutsche-boerse.com/DBRegHub}Currency_Code" minOccurs="0"/>
 *         &lt;element name="complexTradeComponentId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="35"/>
 *               &lt;pattern value="([A-Za-z]|[0-9]){1,35}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirTransaction", propOrder = {
    "trnRefNumber",
    "tradingVenueTrnIdCode",
    "venue",
    "tradeTime",
    "mifirTradingCapacity",
    "quantity",
    "quantityCurrency",
    "notionalIncreaseDecrease",
    "price",
    "priceCurrency",
    "netAmount",
    "upfrontPayment",
    "upfrontPaymentCurrency",
    "complexTradeComponentId"
})
public class MifirTransaction {

    protected String trnRefNumber;
    protected String tradingVenueTrnIdCode;
    @XmlElement(required = true)
    protected String venue;
    protected String tradeTime;
    protected String mifirTradingCapacity;
    protected MifirQuantity quantity;
    protected String quantityCurrency;
    protected String notionalIncreaseDecrease;
    protected MifirPrice price;
    protected String priceCurrency;
    protected String netAmount;
    protected String upfrontPayment;
    protected String upfrontPaymentCurrency;
    protected String complexTradeComponentId;

    /**
     * Gets the value of the trnRefNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrnRefNumber() {
        return trnRefNumber;
    }

    /**
     * Sets the value of the trnRefNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrnRefNumber(String value) {
        this.trnRefNumber = value;
    }

    /**
     * Gets the value of the tradingVenueTrnIdCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradingVenueTrnIdCode() {
        return tradingVenueTrnIdCode;
    }

    /**
     * Sets the value of the tradingVenueTrnIdCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradingVenueTrnIdCode(String value) {
        this.tradingVenueTrnIdCode = value;
    }

    /**
     * Gets the value of the venue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVenue() {
        return venue;
    }

    /**
     * Sets the value of the venue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVenue(String value) {
        this.venue = value;
    }

    /**
     * Gets the value of the tradeTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeTime() {
        return tradeTime;
    }

    /**
     * Sets the value of the tradeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeTime(String value) {
        this.tradeTime = value;
    }

    /**
     * Gets the value of the mifirTradingCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMifirTradingCapacity() {
        return mifirTradingCapacity;
    }

    /**
     * Sets the value of the mifirTradingCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMifirTradingCapacity(String value) {
        this.mifirTradingCapacity = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link MifirQuantity }
     *     
     */
    public MifirQuantity getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link MifirQuantity }
     *     
     */
    public void setQuantity(MifirQuantity value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the quantityCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantityCurrency() {
        return quantityCurrency;
    }

    /**
     * Sets the value of the quantityCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantityCurrency(String value) {
        this.quantityCurrency = value;
    }

    /**
     * Gets the value of the notionalIncreaseDecrease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotionalIncreaseDecrease() {
        return notionalIncreaseDecrease;
    }

    /**
     * Sets the value of the notionalIncreaseDecrease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotionalIncreaseDecrease(String value) {
        this.notionalIncreaseDecrease = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link MifirPrice }
     *     
     */
    public MifirPrice getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link MifirPrice }
     *     
     */
    public void setPrice(MifirPrice value) {
        this.price = value;
    }

    /**
     * Gets the value of the priceCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceCurrency() {
        return priceCurrency;
    }

    /**
     * Sets the value of the priceCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceCurrency(String value) {
        this.priceCurrency = value;
    }

    /**
     * Gets the value of the netAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetAmount() {
        return netAmount;
    }

    /**
     * Sets the value of the netAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetAmount(String value) {
        this.netAmount = value;
    }

    /**
     * Gets the value of the upfrontPayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpfrontPayment() {
        return upfrontPayment;
    }

    /**
     * Sets the value of the upfrontPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpfrontPayment(String value) {
        this.upfrontPayment = value;
    }

    /**
     * Gets the value of the upfrontPaymentCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpfrontPaymentCurrency() {
        return upfrontPaymentCurrency;
    }

    /**
     * Sets the value of the upfrontPaymentCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpfrontPaymentCurrency(String value) {
        this.upfrontPaymentCurrency = value;
    }

    /**
     * Gets the value of the complexTradeComponentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComplexTradeComponentId() {
        return complexTradeComponentId;
    }

    /**
     * Sets the value of the complexTradeComponentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComplexTradeComponentId(String value) {
        this.complexTradeComponentId = value;
    }

}
