//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirBuyerDecisionMakerDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirBuyerDecisionMakerDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="buyerDecisionMakerId" type="{http://deutsche-boerse.com/DBRegHub}buyerSellerDecisionMakerId" minOccurs="0"/>
 *         &lt;element name="buyerDecisionFirstname" type="{http://deutsche-boerse.com/DBRegHub}nameType" minOccurs="0"/>
 *         &lt;element name="buyerDecisionSurname" type="{http://deutsche-boerse.com/DBRegHub}nameType" minOccurs="0"/>
 *         &lt;element name="buyerDecisionBirthdate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="(19|20|21)[0-9]{2}(-)((0)[1-9]|(1)[012])(-)((0)[1-9]|(1|2)[0-9]|(3)[01])"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirBuyerDecisionMakerDetails", propOrder = {
    "buyerDecisionMakerId",
    "buyerDecisionFirstname",
    "buyerDecisionSurname",
    "buyerDecisionBirthdate"
})
public class MifirBuyerDecisionMakerDetails {

    protected BuyerSellerDecisionMakerId buyerDecisionMakerId;
    protected String buyerDecisionFirstname;
    protected String buyerDecisionSurname;
    protected String buyerDecisionBirthdate;

    /**
     * Gets the value of the buyerDecisionMakerId property.
     * 
     * @return
     *     possible object is
     *     {@link BuyerSellerDecisionMakerId }
     *     
     */
    public BuyerSellerDecisionMakerId getBuyerDecisionMakerId() {
        return buyerDecisionMakerId;
    }

    /**
     * Sets the value of the buyerDecisionMakerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyerSellerDecisionMakerId }
     *     
     */
    public void setBuyerDecisionMakerId(BuyerSellerDecisionMakerId value) {
        this.buyerDecisionMakerId = value;
    }

    /**
     * Gets the value of the buyerDecisionFirstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerDecisionFirstname() {
        return buyerDecisionFirstname;
    }

    /**
     * Sets the value of the buyerDecisionFirstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerDecisionFirstname(String value) {
        this.buyerDecisionFirstname = value;
    }

    /**
     * Gets the value of the buyerDecisionSurname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerDecisionSurname() {
        return buyerDecisionSurname;
    }

    /**
     * Sets the value of the buyerDecisionSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerDecisionSurname(String value) {
        this.buyerDecisionSurname = value;
    }

    /**
     * Gets the value of the buyerDecisionBirthdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuyerDecisionBirthdate() {
        return buyerDecisionBirthdate;
    }

    /**
     * Sets the value of the buyerDecisionBirthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuyerDecisionBirthdate(String value) {
        this.buyerDecisionBirthdate = value;
    }

}
