//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirInstrumentDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirInstrumentDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="instrumentId" type="{http://deutsche-boerse.com/DBRegHub}instrumentId" minOccurs="0"/>
 *         &lt;element name="instrumentName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="350"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="instrumentClass" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="notionalCurrency1" type="{http://deutsche-boerse.com/DBRegHub}Currency_Code" minOccurs="0"/>
 *         &lt;element name="notionalCurrency2" type="{http://deutsche-boerse.com/DBRegHub}Currency_Code" minOccurs="0"/>
 *         &lt;element name="priceMultiplier" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="19"/>
 *               &lt;pattern value="((0|[1-9][0-9]{0,17})([.][0-9]{1,17})?)?"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="underlying" type="{http://deutsche-boerse.com/DBRegHub}mifirUnderlying" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="optionType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="PUTO"/>
 *               &lt;enumeration value="CALL"/>
 *               &lt;enumeration value="OTHR"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="strikePrice" type="{http://deutsche-boerse.com/DBRegHub}mifirStrikePrice" minOccurs="0"/>
 *         &lt;element name="strikePriceCurrency" type="{http://deutsche-boerse.com/DBRegHub}Currency_Code" minOccurs="0"/>
 *         &lt;element name="optionExerciseStyle" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="EURO"/>
 *               &lt;enumeration value="AMER"/>
 *               &lt;enumeration value="ASIA"/>
 *               &lt;enumeration value="BERM"/>
 *               &lt;enumeration value="OTHR"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="maturityDateInstrument" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="(19|20|21|99)[0-9]{2}(-)((0)[1-9]|(1)[012])(-)((0)[1-9]|(1|2)[0-9]|(3)[01])"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="expiryDate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="(19|20|21)[0-9]{2}(-)((0)[1-9]|(1)[012])(-)((0)[1-9]|(1|2)[0-9]|(3)[01])"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="deliveryType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="PHYS"/>
 *               &lt;enumeration value="CASH"/>
 *               &lt;enumeration value="OPTL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirInstrumentDetails", propOrder = {
    "instrumentId",
    "instrumentName",
    "instrumentClass",
    "notionalCurrency1",
    "notionalCurrency2",
    "priceMultiplier",
    "underlying",
    "optionType",
    "strikePrice",
    "strikePriceCurrency",
    "optionExerciseStyle",
    "maturityDateInstrument",
    "expiryDate",
    "deliveryType"
})
public class MifirInstrumentDetails {

    protected InstrumentId instrumentId;
    protected String instrumentName;
    protected String instrumentClass;
    protected String notionalCurrency1;
    protected String notionalCurrency2;
    protected String priceMultiplier;
    protected List<MifirUnderlying> underlying;
    protected String optionType;
    protected MifirStrikePrice strikePrice;
    protected String strikePriceCurrency;
    protected String optionExerciseStyle;
    protected String maturityDateInstrument;
    protected String expiryDate;
    protected String deliveryType;

    /**
     * Gets the value of the instrumentId property.
     * 
     * @return
     *     possible object is
     *     {@link InstrumentId }
     *     
     */
    public InstrumentId getInstrumentId() {
        return instrumentId;
    }

    /**
     * Sets the value of the instrumentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstrumentId }
     *     
     */
    public void setInstrumentId(InstrumentId value) {
        this.instrumentId = value;
    }

    /**
     * Gets the value of the instrumentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentName() {
        return instrumentName;
    }

    /**
     * Sets the value of the instrumentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentName(String value) {
        this.instrumentName = value;
    }

    /**
     * Gets the value of the instrumentClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentClass() {
        return instrumentClass;
    }

    /**
     * Sets the value of the instrumentClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentClass(String value) {
        this.instrumentClass = value;
    }

    /**
     * Gets the value of the notionalCurrency1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotionalCurrency1() {
        return notionalCurrency1;
    }

    /**
     * Sets the value of the notionalCurrency1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotionalCurrency1(String value) {
        this.notionalCurrency1 = value;
    }

    /**
     * Gets the value of the notionalCurrency2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotionalCurrency2() {
        return notionalCurrency2;
    }

    /**
     * Sets the value of the notionalCurrency2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotionalCurrency2(String value) {
        this.notionalCurrency2 = value;
    }

    /**
     * Gets the value of the priceMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriceMultiplier() {
        return priceMultiplier;
    }

    /**
     * Sets the value of the priceMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriceMultiplier(String value) {
        this.priceMultiplier = value;
    }

    /**
     * Gets the value of the underlying property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the underlying property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnderlying().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MifirUnderlying }
     * 
     * 
     */
    public List<MifirUnderlying> getUnderlying() {
        if (underlying == null) {
            underlying = new ArrayList<MifirUnderlying>();
        }
        return this.underlying;
    }

    /**
     * Gets the value of the optionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionType() {
        return optionType;
    }

    /**
     * Sets the value of the optionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionType(String value) {
        this.optionType = value;
    }

    /**
     * Gets the value of the strikePrice property.
     * 
     * @return
     *     possible object is
     *     {@link MifirStrikePrice }
     *     
     */
    public MifirStrikePrice getStrikePrice() {
        return strikePrice;
    }

    /**
     * Sets the value of the strikePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link MifirStrikePrice }
     *     
     */
    public void setStrikePrice(MifirStrikePrice value) {
        this.strikePrice = value;
    }

    /**
     * Gets the value of the strikePriceCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrikePriceCurrency() {
        return strikePriceCurrency;
    }

    /**
     * Sets the value of the strikePriceCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrikePriceCurrency(String value) {
        this.strikePriceCurrency = value;
    }

    /**
     * Gets the value of the optionExerciseStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionExerciseStyle() {
        return optionExerciseStyle;
    }

    /**
     * Sets the value of the optionExerciseStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionExerciseStyle(String value) {
        this.optionExerciseStyle = value;
    }

    /**
     * Gets the value of the maturityDateInstrument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaturityDateInstrument() {
        return maturityDateInstrument;
    }

    /**
     * Sets the value of the maturityDateInstrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaturityDateInstrument(String value) {
        this.maturityDateInstrument = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryDate(String value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the deliveryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryType() {
        return deliveryType;
    }

    /**
     * Sets the value of the deliveryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryType(String value) {
        this.deliveryType = value;
    }

}
