//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirSellerDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirSellerDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sellerId" type="{http://deutsche-boerse.com/DBRegHub}buyerSellerId"/>
 *         &lt;element name="sellerBranchCountry" type="{http://deutsche-boerse.com/DBRegHub}Country_Code" minOccurs="0"/>
 *         &lt;element name="sellerFirstname" type="{http://deutsche-boerse.com/DBRegHub}nameType" minOccurs="0"/>
 *         &lt;element name="sellerSurname" type="{http://deutsche-boerse.com/DBRegHub}nameType" minOccurs="0"/>
 *         &lt;element name="sellerBirthdate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="(17|18|19|20|21)[0-9]{2}(-)((0)[1-9]|(1)[012])(-)((0)[1-9]|(1|2)[0-9]|(3)[01])"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirSellerDetails", propOrder = {
    "sellerId",
    "sellerBranchCountry",
    "sellerFirstname",
    "sellerSurname",
    "sellerBirthdate"
})
public class MifirSellerDetails {

    @XmlElement(required = true)
    protected BuyerSellerId sellerId;
    protected String sellerBranchCountry;
    protected String sellerFirstname;
    protected String sellerSurname;
    protected String sellerBirthdate;

    /**
     * Gets the value of the sellerId property.
     * 
     * @return
     *     possible object is
     *     {@link BuyerSellerId }
     *     
     */
    public BuyerSellerId getSellerId() {
        return sellerId;
    }

    /**
     * Sets the value of the sellerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyerSellerId }
     *     
     */
    public void setSellerId(BuyerSellerId value) {
        this.sellerId = value;
    }

    /**
     * Gets the value of the sellerBranchCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerBranchCountry() {
        return sellerBranchCountry;
    }

    /**
     * Sets the value of the sellerBranchCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerBranchCountry(String value) {
        this.sellerBranchCountry = value;
    }

    /**
     * Gets the value of the sellerFirstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerFirstname() {
        return sellerFirstname;
    }

    /**
     * Sets the value of the sellerFirstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerFirstname(String value) {
        this.sellerFirstname = value;
    }

    /**
     * Gets the value of the sellerSurname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerSurname() {
        return sellerSurname;
    }

    /**
     * Sets the value of the sellerSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerSurname(String value) {
        this.sellerSurname = value;
    }

    /**
     * Gets the value of the sellerBirthdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerBirthdate() {
        return sellerBirthdate;
    }

    /**
     * Sets the value of the sellerBirthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerBirthdate(String value) {
        this.sellerBirthdate = value;
    }

}
