//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirSellerDecisionMakerDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirSellerDecisionMakerDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sellerDecisionMakerId" type="{http://deutsche-boerse.com/DBRegHub}buyerSellerDecisionMakerId" minOccurs="0"/>
 *         &lt;element name="sellerDecisionFirstname" type="{http://deutsche-boerse.com/DBRegHub}nameType" minOccurs="0"/>
 *         &lt;element name="sellerDecisionSurname" type="{http://deutsche-boerse.com/DBRegHub}nameType" minOccurs="0"/>
 *         &lt;element name="sellerDecisionBirthdate" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="(19|20|21)[0-9]{2}(-)((0)[1-9]|(1)[012])(-)((0)[1-9]|(1|2)[0-9]|(3)[01])"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirSellerDecisionMakerDetails", propOrder = {
    "sellerDecisionMakerId",
    "sellerDecisionFirstname",
    "sellerDecisionSurname",
    "sellerDecisionBirthdate"
})
public class MifirSellerDecisionMakerDetails {

    protected BuyerSellerDecisionMakerId sellerDecisionMakerId;
    protected String sellerDecisionFirstname;
    protected String sellerDecisionSurname;
    protected String sellerDecisionBirthdate;

    /**
     * Gets the value of the sellerDecisionMakerId property.
     * 
     * @return
     *     possible object is
     *     {@link BuyerSellerDecisionMakerId }
     *     
     */
    public BuyerSellerDecisionMakerId getSellerDecisionMakerId() {
        return sellerDecisionMakerId;
    }

    /**
     * Sets the value of the sellerDecisionMakerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyerSellerDecisionMakerId }
     *     
     */
    public void setSellerDecisionMakerId(BuyerSellerDecisionMakerId value) {
        this.sellerDecisionMakerId = value;
    }

    /**
     * Gets the value of the sellerDecisionFirstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerDecisionFirstname() {
        return sellerDecisionFirstname;
    }

    /**
     * Sets the value of the sellerDecisionFirstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerDecisionFirstname(String value) {
        this.sellerDecisionFirstname = value;
    }

    /**
     * Gets the value of the sellerDecisionSurname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerDecisionSurname() {
        return sellerDecisionSurname;
    }

    /**
     * Sets the value of the sellerDecisionSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerDecisionSurname(String value) {
        this.sellerDecisionSurname = value;
    }

    /**
     * Gets the value of the sellerDecisionBirthdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerDecisionBirthdate() {
        return sellerDecisionBirthdate;
    }

    /**
     * Sets the value of the sellerDecisionBirthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerDecisionBirthdate(String value) {
        this.sellerDecisionBirthdate = value;
    }

}
