//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirUnderlyingIndex complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirUnderlyingIndex">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="underlyingIndexDirection" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="+"/>
 *               &lt;enumeration value="-"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="underlyingIndexCode" type="{http://deutsche-boerse.com/DBRegHub}ISIN" minOccurs="0"/>
 *         &lt;element name="underlyingIndexName" type="{http://deutsche-boerse.com/DBRegHub}mifirUnderlyingIndexName"/>
 *         &lt;element name="underlyingIndexTerm" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="underlyingIndexTermUnit" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;enumeration value="DAYS"/>
 *               &lt;enumeration value="WEEK"/>
 *               &lt;enumeration value="MNTH"/>
 *               &lt;enumeration value="YEAR"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirUnderlyingIndex", propOrder = {
    "underlyingIndexDirection",
    "underlyingIndexCode",
    "underlyingIndexName",
    "underlyingIndexTerm",
    "underlyingIndexTermUnit"
})
public class MifirUnderlyingIndex {

    protected String underlyingIndexDirection;
    protected String underlyingIndexCode;
    @XmlElement(required = true)
    protected MifirUnderlyingIndexName underlyingIndexName;
    protected BigInteger underlyingIndexTerm;
    protected String underlyingIndexTermUnit;

    /**
     * Gets the value of the underlyingIndexDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnderlyingIndexDirection() {
        return underlyingIndexDirection;
    }

    /**
     * Sets the value of the underlyingIndexDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnderlyingIndexDirection(String value) {
        this.underlyingIndexDirection = value;
    }

    /**
     * Gets the value of the underlyingIndexCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnderlyingIndexCode() {
        return underlyingIndexCode;
    }

    /**
     * Sets the value of the underlyingIndexCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnderlyingIndexCode(String value) {
        this.underlyingIndexCode = value;
    }

    /**
     * Gets the value of the underlyingIndexName property.
     * 
     * @return
     *     possible object is
     *     {@link MifirUnderlyingIndexName }
     *     
     */
    public MifirUnderlyingIndexName getUnderlyingIndexName() {
        return underlyingIndexName;
    }

    /**
     * Sets the value of the underlyingIndexName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MifirUnderlyingIndexName }
     *     
     */
    public void setUnderlyingIndexName(MifirUnderlyingIndexName value) {
        this.underlyingIndexName = value;
    }

    /**
     * Gets the value of the underlyingIndexTerm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUnderlyingIndexTerm() {
        return underlyingIndexTerm;
    }

    /**
     * Sets the value of the underlyingIndexTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUnderlyingIndexTerm(BigInteger value) {
        this.underlyingIndexTerm = value;
    }

    /**
     * Gets the value of the underlyingIndexTermUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnderlyingIndexTermUnit() {
        return underlyingIndexTermUnit;
    }

    /**
     * Sets the value of the underlyingIndexTermUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnderlyingIndexTermUnit(String value) {
        this.underlyingIndexTermUnit = value;
    }

}
