//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mifirTransmission complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mifirTransmission">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transmissionId" type="{http://deutsche-boerse.com/DBRegHub}YesNo" minOccurs="0"/>
 *         &lt;element name="transmittingEntityBuyerId" type="{http://deutsche-boerse.com/DBRegHub}LEId" minOccurs="0"/>
 *         &lt;element name="transmittingEntitySellerId" type="{http://deutsche-boerse.com/DBRegHub}LEId" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mifirTransmission", propOrder = {
    "transmissionId",
    "transmittingEntityBuyerId",
    "transmittingEntitySellerId"
})
public class MifirTransmission {

    @XmlSchemaType(name = "string")
    protected YesNo transmissionId;
    protected LEId transmittingEntityBuyerId;
    protected LEId transmittingEntitySellerId;

    /**
     * Gets the value of the transmissionId property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getTransmissionId() {
        return transmissionId;
    }

    /**
     * Sets the value of the transmissionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setTransmissionId(YesNo value) {
        this.transmissionId = value;
    }

    /**
     * Gets the value of the transmittingEntityBuyerId property.
     * 
     * @return
     *     possible object is
     *     {@link LEId }
     *     
     */
    public LEId getTransmittingEntityBuyerId() {
        return transmittingEntityBuyerId;
    }

    /**
     * Sets the value of the transmittingEntityBuyerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEId }
     *     
     */
    public void setTransmittingEntityBuyerId(LEId value) {
        this.transmittingEntityBuyerId = value;
    }

    /**
     * Gets the value of the transmittingEntitySellerId property.
     * 
     * @return
     *     possible object is
     *     {@link LEId }
     *     
     */
    public LEId getTransmittingEntitySellerId() {
        return transmittingEntitySellerId;
    }

    /**
     * Sets the value of the transmittingEntitySellerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link LEId }
     *     
     */
    public void setTransmittingEntitySellerId(LEId value) {
        this.transmittingEntitySellerId = value;
    }

}
