//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 02:21:55 PM BST 
//


package com.trax.europeangateway.model.dto.xsd.omega;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.trax.europeangateway.model.xsddto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.trax.europeangateway.model.xsddto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReportFile }
     * 
     */
    public ReportFile createReportFile() {
        return new ReportFile();
    }

    /**
     * Create an instance of {@link FileInformation }
     * 
     */
    public FileInformation createFileInformation() {
        return new FileInformation();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link MifirStrikePrice }
     * 
     */
    public MifirStrikePrice createMifirStrikePrice() {
        return new MifirStrikePrice();
    }

    /**
     * Create an instance of {@link InstrumentId }
     * 
     */
    public InstrumentId createInstrumentId() {
        return new InstrumentId();
    }

    /**
     * Create an instance of {@link MifirBuyerDecisionMakerDetails }
     * 
     */
    public MifirBuyerDecisionMakerDetails createMifirBuyerDecisionMakerDetails() {
        return new MifirBuyerDecisionMakerDetails();
    }

    /**
     * Create an instance of {@link MifirDelegation }
     * 
     */
    public MifirDelegation createMifirDelegation() {
        return new MifirDelegation();
    }

    /**
     * Create an instance of {@link InvestmentExecutionId }
     * 
     */
    public InvestmentExecutionId createInvestmentExecutionId() {
        return new InvestmentExecutionId();
    }

    /**
     * Create an instance of {@link MifirTransmission }
     * 
     */
    public MifirTransmission createMifirTransmission() {
        return new MifirTransmission();
    }

    /**
     * Create an instance of {@link MifirDetails }
     * 
     */
    public MifirDetails createMifirDetails() {
        return new MifirDetails();
    }

    /**
     * Create an instance of {@link LEId }
     * 
     */
    public LEId createLEId() {
        return new LEId();
    }

    /**
     * Create an instance of {@link TransactionPositionReport }
     * 
     */
    public TransactionPositionReport createTransactionPositionReport() {
        return new TransactionPositionReport();
    }

    /**
     * Create an instance of {@link MifirCounterpartyDetails }
     * 
     */
    public MifirCounterpartyDetails createMifirCounterpartyDetails() {
        return new MifirCounterpartyDetails();
    }

    /**
     * Create an instance of {@link MifirSellerDetails }
     * 
     */
    public MifirSellerDetails createMifirSellerDetails() {
        return new MifirSellerDetails();
    }

    /**
     * Create an instance of {@link MifirSeller }
     * 
     */
    public MifirSeller createMifirSeller() {
        return new MifirSeller();
    }

    /**
     * Create an instance of {@link MifirUnderlyingIndexName }
     * 
     */
    public MifirUnderlyingIndexName createMifirUnderlyingIndexName() {
        return new MifirUnderlyingIndexName();
    }

    /**
     * Create an instance of {@link MifirBuyer }
     * 
     */
    public MifirBuyer createMifirBuyer() {
        return new MifirBuyer();
    }

    /**
     * Create an instance of {@link ReferencePartyDetails }
     * 
     */
    public ReferencePartyDetails createReferencePartyDetails() {
        return new ReferencePartyDetails();
    }

    /**
     * Create an instance of {@link MifirOtherDetails }
     * 
     */
    public MifirOtherDetails createMifirOtherDetails() {
        return new MifirOtherDetails();
    }

    /**
     * Create an instance of {@link MifirUnderlying }
     * 
     */
    public MifirUnderlying createMifirUnderlying() {
        return new MifirUnderlying();
    }

    /**
     * Create an instance of {@link MifirUnderlyingIndex }
     * 
     */
    public MifirUnderlyingIndex createMifirUnderlyingIndex() {
        return new MifirUnderlyingIndex();
    }

    /**
     * Create an instance of {@link BuyerSellerId }
     * 
     */
    public BuyerSellerId createBuyerSellerId() {
        return new BuyerSellerId();
    }

    /**
     * Create an instance of {@link MifirBuyerDetails }
     * 
     */
    public MifirBuyerDetails createMifirBuyerDetails() {
        return new MifirBuyerDetails();
    }

    /**
     * Create an instance of {@link MifirUnderlyingInstrument }
     * 
     */
    public MifirUnderlyingInstrument createMifirUnderlyingInstrument() {
        return new MifirUnderlyingInstrument();
    }

    /**
     * Create an instance of {@link InvestmentDecisionId }
     * 
     */
    public InvestmentDecisionId createInvestmentDecisionId() {
        return new InvestmentDecisionId();
    }

    /**
     * Create an instance of {@link MifirPrice }
     * 
     */
    public MifirPrice createMifirPrice() {
        return new MifirPrice();
    }

    /**
     * Create an instance of {@link ProcessingDetails }
     * 
     */
    public ProcessingDetails createProcessingDetails() {
        return new ProcessingDetails();
    }

    /**
     * Create an instance of {@link ConfigurableFields }
     * 
     */
    public ConfigurableFields createConfigurableFields() {
        return new ConfigurableFields();
    }

    /**
     * Create an instance of {@link PartyCodeType }
     * 
     */
    public PartyCodeType createPartyCodeType() {
        return new PartyCodeType();
    }

    /**
     * Create an instance of {@link MifirSellerDecisionMakerDetails }
     * 
     */
    public MifirSellerDecisionMakerDetails createMifirSellerDecisionMakerDetails() {
        return new MifirSellerDecisionMakerDetails();
    }

    /**
     * Create an instance of {@link MifirTransaction }
     * 
     */
    public MifirTransaction createMifirTransaction() {
        return new MifirTransaction();
    }

    /**
     * Create an instance of {@link MifirInstrumentDetails }
     * 
     */
    public MifirInstrumentDetails createMifirInstrumentDetails() {
        return new MifirInstrumentDetails();
    }

    /**
     * Create an instance of {@link BuyerSellerDecisionMakerId }
     * 
     */
    public BuyerSellerDecisionMakerId createBuyerSellerDecisionMakerId() {
        return new BuyerSellerDecisionMakerId();
    }

    /**
     * Create an instance of {@link MifirQuantity }
     * 
     */
    public MifirQuantity createMifirQuantity() {
        return new MifirQuantity();
    }

}
